version: '3.8'

services:
  nrrc-arabic-pov:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./conf:/app/conf
    environment:
      - PYTHONIOENCODING=utf-8
      - TRANSFORMERS_CACHE=/app/.cache/transformers
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
